### ISSUE TITLE
Head Area abbr

### ISSUE THREAD

**Issue by meghalithic** [hdr-bgnn/Morphology-analysis#13]
HA_p is used if calculating area using pixels
HA_t is used if creating a triangle and then calculating area inside the triangle

**Comment by thibaulttabarin** [comment]
yes but actually in the code is Hap and Hat, what is better. easy to change in the code

**Comment by thibaulttabarin** [comment]
Ok I did realise HA_p stand for Head area pixel, i think the name is inappropriate because the other measure used as well pixels. Therefore Ha_t is good name ( for Head Area triangle) for the other we could say Head Area full (HA_f) or real (HA_r) or accurate (HA_a), mask (HA_m), or just HA.
Something to say that we use the full head mask... I would say HA seem the best because it you ask me without any specification to calculate Head Area I would do this way (what currently is noted HA_p

**Comment by thibaulttabarin** [comment]
for now I choose HA, if you prefer something else let me know I will update the code. And please update the measurement_v1.csv
Cheers

**Comment by meghalithic** [comment]
Let's use HA_m to mean the segmentation (head + eye) was used and not the triangle

**Comment by meghalithic** [comment]
@thibaulttabarin I will change it in v1, if you could change it in the code
